const $ = (selector, root = document) => root.querySelector(selector);
const state = { projects: [], workspaces: [], sessions: [], archivedSessions: [], capabilities: new Map(), scopes: new Map(), current: false, pending: new Set(), apiToken: null };
let socket;
const supported = ["scope.host","scope.session","session.create","session.rename","session.archive","session.restore","session.fork","run.submit","run.follow-up","run.steer","run.release","run.cancel","run.stop","pi.model.select","pi.mode.select","pi.input.text","presentation.effects","pi.interaction.basic"];
const pairingSecret = new URL(location.href).searchParams.get("pair");

function send(command) { if (!state.current || !socket || socket.readyState !== WebSocket.OPEN) return false; command.commandId ??= crypto.randomUUID(); state.pending.add(command.commandId); socket.send(JSON.stringify(command)); renderCurrentView(); return true; }
function navigate(path) { history.pushState({}, "", path); route(); }
document.addEventListener("click", event => { const link = event.target.closest("[data-route]"); if (link) { event.preventDefault(); navigate(link.pathname); } });
addEventListener("popstate", route);
addEventListener("offline", () => setCurrent(false, "Offline · cached state may be stale"));
addEventListener("online", () => { setCurrent(false, "Reconnecting"); authenticateStoredDevice(); });
addEventListener("visibilitychange", () => { if (document.hidden) setCurrent(false, "Stale · return to reconcile"); else if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type:"scope.set", sessionIds: currentSessionId() ? [currentSessionId()] : [], protocolVersion:"1.1" })); });

$("#new-session").onclick = () => $("#new-session-view").showModal();
$("#session-search").oninput = renderSidebar;
$("#session-project").onchange = renderWorkspaceOptions;
$("#create-session").onclick = () => createSession("");
$("#create-and-run").onclick = () => createSession($("#new-prompt").value.trim());

if (pairingSecret) { history.replaceState({}, "", location.pathname); $("#pairing").hidden = false; $("#content").hidden = true; $("#pair-device").onclick = pairDevice; } else authenticateStoredDevice();

async function pairDevice() { const keys = await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},false,["sign","verify"]); const publicKey = await crypto.subtle.exportKey("jwk",keys.publicKey); const challenge = await post("/pair/challenge",{secret:pairingSecret,publicKey}); const signature = await sign(keys.privateKey,challenge.challenge); const device = await post("/pair/complete",{pairingId:challenge.pairingId,signature:b64(signature)}); await saveDevice({deviceId:device.deviceId,privateKey:keys.privateKey}); location.href="/"; }
async function authenticateStoredDevice() { const device = await loadDevice(); if (!device) { setCurrent(false,"Pairing required"); return; } try { const challenge=await post("/pair/auth-challenge",{deviceId:device.deviceId}); const signature=await sign(device.privateKey,challenge.challenge); const auth=await post("/pair/authenticate",{authenticationId:challenge.authenticationId,signature:b64(signature)}); state.apiToken=auth.session; openControl(auth.session); } catch { setCurrent(false,"Offline · cached state may be stale"); } }
function openControl(token) { socket?.close(); socket=new WebSocket(`wss://${location.host}/control?session=${encodeURIComponent(token)}`); socket.onmessage=event=>handle(JSON.parse(event.data)); socket.onclose=()=>setCurrent(false,"Offline · cached state may be stale"); }
function handle(message) {
  if(message.type==="host.hello") return socket.send(JSON.stringify({type:"client.hello",expectedHostId:localStorage.getItem("pidex.expectedHostId")||message.hostId,protocols:[{major:1,minor:1}],capabilities:supported.map(id=>({id,minVersion:1,maxVersion:1}))}));
  if(message.type==="protocol.admitted") { state.capabilities=new Map(message.capabilities.map(c=>[c.id,c])); return; }
  if(message.type==="host.snapshot") { Object.assign(state,{projects:message.projects,workspaces:message.workspaces,sessions:message.sessions,archivedSessions:message.archivedSessions}); localStorage.setItem("pidex.expectedHostId",message.status.hostId); $("#device-state").textContent=`Device · ${message.status.hostId}`; setCurrent(true,"Current"); renderCatalogControls(); route(); return; }
  if(message.type==="host.change-set") { for(const c of message.changes) applyChange(c); renderSidebar(); renderCurrentView(); return; }
  if(message.type==="scope.reset" && message.barrier.scope.kind==="session") { state.scopes.set(message.barrier.scope.sessionId,{...message.snapshot,timeline:[...(message.snapshot.timelineWindow?.entries||message.snapshot.timeline||[])],olderCursor:message.snapshot.timelineWindow?.olderCursor||null}); setCurrent(true,"Current"); renderCurrentView(); return; }
  if(message.type==="scope.current") { setCurrent(true,"Current"); return; }
  if(message.type==="timeline.change") { const scope=state.scopes.get(message.sessionId); if(scope){ const i=scope.timeline.findIndex(e=>e.entryId===message.entry.entryId); i<0?scope.timeline.push(message.entry):scope.timeline.splice(i,1,message.entry); renderCurrentView(); } return; }
  if(message.type==="interaction.change") { const scope=state.scopes.get(message.interaction.sessionId); if(scope){ const i=(scope.interactions||=[]).findIndex(x=>x.interactionId===message.interaction.interactionId); i<0?scope.interactions.push(message.interaction):scope.interactions.splice(i,1,message.interaction); renderCurrentView(); } return; }
  if(message.type==="run.execution"||message.type==="run.completed") { const id=message.sessionId||message.run.sessionId; const scope=state.scopes.get(id); if(scope){ const run=message.run||{...message,runId:message.runId}; const i=(scope.runs||=[]).findIndex(x=>x.runId===run.runId); i<0?scope.runs.push(run):scope.runs.splice(i,1,run); renderSidebar(); renderCurrentView(); } return; }
  if(message.type==="command.outcome") { state.pending.delete(message.commandId); if(message.outcome==="rejected") announce(`Command rejected: ${message.error}`); renderCurrentView(); }
  if(message.type==="protocol.update-required"||message.type==="delivery.resynchronize") setCurrent(false,message.type==="protocol.update-required"?"Update required":"Resynchronizing");
}
function applyChange(c){ state.sessions=state.sessions.filter(s=>s.sessionId!==c.session.sessionId);state.archivedSessions=state.archivedSessions.filter(s=>s.sessionId!==c.session.sessionId);if(c.type==="session.archived")state.archivedSessions.push(c.session);else state.sessions.push(c.session); }
function setCurrent(value,label){state.current=value;$("#connection-state").textContent=label;document.body.classList.toggle("stale",!value);renderCurrentView();}
function renderCatalogControls(){ $("#session-project").replaceChildren(new Option("Host-unscoped",""),...state.projects.map(p=>new Option(p.name,p.projectId))); renderWorkspaceOptions(); }
function renderWorkspaceOptions(){const id=$("#session-project").value;$("#session-workspace").replaceChildren(new Option("No Workspace",""),...state.workspaces.filter(w=>w.projectId===id).map(w=>new Option(w.name,w.workspaceId)));}
function createSession(prompt){ const id=crypto.randomUUID(); const command={type:"session.create",commandId:id,projectId:$("#session-project").value||null,workspaceId:$("#session-workspace").value||null}; if(send(command)){ $("#new-session-view").close(); $("#new-prompt").value=""; if(prompt){ const wait=setInterval(()=>{const created=state.sessions.at(-1);if(created){clearInterval(wait);navigate(`/sessions/${created.sessionId}`);send({type:"run.submit",sessionId:created.sessionId,prompt,requiredCapability:"run.submit"});}},50); setTimeout(()=>clearInterval(wait),5000); } } }
function route(){renderSidebar(); const id=currentSessionId(); if(id&&socket?.readyState===WebSocket.OPEN){state.current=false;$("#connection-state").textContent="Reconciling Session";socket.send(JSON.stringify({type:"scope.set",sessionIds:[id],protocolVersion:"1.1"}));} renderCurrentView();}
function renderSidebar(){const archived=location.pathname==="/archived";const query=$("#session-search").value.toLowerCase();const sessions=(archived?state.archivedSessions:state.sessions).filter(s=>`${s.name} ${groupName(s)}`.toLowerCase().includes(query));const groups=new Map();for(const s of sessions.sort((a,b)=>b.timelineRevision-a.timelineRevision)){const key=groupName(s);groups.set(key,[...(groups.get(key)||[]),s]);}$("#sessions").replaceChildren(...[...groups].flatMap(([name,list])=>{const h=document.createElement("h2");h.textContent=name;return[h,...list.map(sessionLink)];}));}
function sessionLink(s){const a=document.createElement("a");a.href=`/sessions/${s.sessionId}`;a.dataset.route="";a.className="session-link";a.setAttribute("aria-current",currentSessionId()===s.sessionId?"page":"false");const cue=sessionCue(s);a.append(document.createTextNode(s.name));const small=document.createElement("small");small.textContent=cue;a.append(small);return a;}
function sessionCue(s){const scope=state.scopes.get(s.sessionId);const runs=scope?.runs||[];const interactions=(scope?.interactions||[]).filter(i=>["open","resolving"].includes(i.state));if(runs.some(r=>["executing","cancelling"].includes(r.state)))return "● Run executing";if(interactions.length)return `◆ ${interactions.length} open Interaction${interactions.length>1?"s":""}`;if(runs.some(r=>r.state==="held"))return "Held work";if(runs.some(r=>r.state==="queued"))return "Queued work";const last=[...runs].reverse().find(r=>["failed","cancelled","interrupted"].includes(r.state));if(last)return `Last Run ${last.state}`;return s.residency==="sleeping"?"Sleeping":"Resident";}
function renderCurrentView(){const content=$("#content");if(location.pathname==="/archived"){content.innerHTML=`<header class="view-header"><div><h1>Archived Sessions</h1><div class="scope">Readable, restorable Fork parents</div></div></header>`;for(const s of state.archivedSessions){const b=document.createElement("button");b.textContent=`Restore ${s.name}`;b.disabled=!can("session.restore");b.onclick=()=>send({type:"session.restore",sessionId:s.sessionId,observedMetadataRevision:s.metadataRevision});content.append(b);}return;}const id=currentSessionId(),session=state.sessions.find(s=>s.sessionId===id)||state.archivedSessions.find(s=>s.sessionId===id);if(!session){content.innerHTML='<div class="empty"><h1>Pidex</h1><p>Choose a Session or start something new.</p></div>';return;}content.replaceChildren($("#session-view").content.cloneNode(true));$("#session-title").textContent=session.name;$("#session-scope").textContent=`${groupName(session)} · ${session.sessionId}`;wireSession(session);}
function wireSession(session){const scope=state.scopes.get(session.sessionId);const timeline=$("#timeline");if(!scope)timeline.textContent="Loading complete Timeline…";else timeline.replaceChildren(...scope.timeline.map(entryNode));const older=$("#older-timeline");older.hidden=!scope?.olderCursor;older.onclick=()=>loadOlder(session.sessionId,scope);const open=(scope?.interactions||[]).filter(i=>["open","resolving"].includes(i.state));renderInteractions(open);const runs=scope?.runs||[];const executing=runs.find(r=>["executing","cancelling"].includes(r.state));const queued=runs.find(r=>r.state==="queued");const held=runs.find(r=>r.state==="held");const input=$("#run-input");input.disabled=!state.current;$("#composer-state").textContent=state.current?sessionCue(session):$("#connection-state").textContent;$("#submit-run").disabled=!can(executing?"run.follow-up":"run.submit");$("#submit-run").textContent=executing?"Queue follow-up":"Run";$("#submit-run").onclick=()=>{if(input.value.trim()&&send({type:executing?"run.follow-up":"run.submit",sessionId:session.sessionId,prompt:input.value,requiredCapability:executing?"run.follow-up":"run.submit"}))input.value="";};const stop=$("#stop-run");stop.hidden=!executing?.workerGeneration||!can("run.stop");stop.onclick=()=>send({type:"run.stop",sessionId:session.sessionId,runId:executing.runId,workerGeneration:executing.workerGeneration,observedState:"executing",observedTimelineRevision:session.timelineRevision,requiredCapability:"run.stop"});queueButton("#release-run",held,"run.release");queueButton("#cancel-run",held||queued,"run.cancel");$("#rename-session").hidden=!can("session.rename");$("#rename-session").onclick=()=>{const name=prompt("Session name",session.name);if(name?.trim())send({type:"session.rename",sessionId:session.sessionId,name:name.trim(),requiredCapability:"session.rename",observedMetadataRevision:session.metadataRevision});};$("#archive-session").hidden=session.availability==="archived"||!can("session.archive");$("#archive-session").onclick=()=>send({type:"session.archive",sessionId:session.sessionId,observedMetadataRevision:session.metadataRevision});$("#fork-session").hidden=!can("session.fork");$("#fork-session").onclick=()=>{const point=[...(scope?.timeline||[])].reverse().find(e=>e.finalized);if(point)send({type:"session.fork",parentSessionId:session.sessionId,forkPointEntryId:point.entryId});else announce("No stable Fork point is available");};for(const [id,el] of [["pi.model.select",$("#run-model")],["pi.mode.select",$("#run-mode")]]){const cap=state.capabilities.get(id);el.hidden=!cap;if(cap)el.replaceChildren(...(cap.constraints?.values||[]).map(v=>new Option(v,v)));}}
function queueButton(selector,run,type){const b=$(selector);b.hidden=!run||!can(type);b.onclick=()=>send({type,runId:run.runId});}
function renderInteractions(items){const area=$("#interaction");area.hidden=!items.length;if(!items.length)return;let index=0;const draw=()=>{const i=items[index];area.replaceChildren();const title=document.createElement("strong");title.textContent=`Interaction ${index+1} of ${items.length}`;const p=document.createElement("p");p.textContent=i.payload.message;const control=i.kind==="select"?document.createElement("select"):i.kind==="confirm"?document.createElement("input"):document.createElement("textarea");if(i.kind==="select")control.replaceChildren(...i.payload.options.map(v=>new Option(v,v)));if(i.kind==="confirm")control.type="checkbox";const respond=document.createElement("button");respond.textContent="Respond";respond.onclick=()=>send({type:"interaction.resolve",interactionId:i.interactionId,workerGeneration:i.workerGeneration,observedRevision:i.revision,dismiss:false,value:i.kind==="confirm"?control.checked:control.value});const dismiss=document.createElement("button");dismiss.textContent="Dismiss";dismiss.onclick=()=>send({type:"interaction.resolve",interactionId:i.interactionId,workerGeneration:i.workerGeneration,observedRevision:i.revision,dismiss:true});const next=document.createElement("button");next.textContent="Next";next.disabled=items.length<2;next.onclick=()=>{index=(index+1)%items.length;draw();};area.append(title,p,control,respond,dismiss,next);};draw();}
function entryNode(e){const div=document.createElement("article");div.className="entry";div.dataset.kind=e.kind;const meta=document.createElement("div");meta.className="entry-meta";meta.textContent=`${e.kind}${e.finalized?"":" · streaming"}`;const text=document.createElement("div");text.textContent=e.text;div.append(meta,text);return div;}
async function loadOlder(id,scope){const response=await fetch(`/api/sessions/${encodeURIComponent(id)}/timeline?cursor=${encodeURIComponent(scope.olderCursor)}&limit=100`,{headers:{authorization:`Bearer ${state.apiToken}`}});if(response.ok){const page=await response.json();scope.timeline=[...page.entries,...scope.timeline];scope.olderCursor=page.olderCursor;renderCurrentView();}}
function can(id){return state.current&&state.capabilities.has(id)&&!state.pending.size;}function currentSessionId(){return location.pathname.match(/^\/sessions\/([^/]+)$/)?.[1];}function groupName(s){const p=state.projects.find(x=>x.projectId===s.projectId),w=state.workspaces.find(x=>x.workspaceId===s.workspaceId);return w?`${p?.name} / ${w.name}`:p?`${p.name} / Project Sessions`:"Host-unscoped";}function announce(text){$("#composer-state")?$("#composer-state").textContent=text:alert(text);}
async function post(path,body){const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),credentials:"omit"});const value=await r.json();if(!r.ok)throw Error(value.error);return value;}function sign(key,text){return crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,new TextEncoder().encode(text));}function b64(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"");}
function store(mode){return new Promise((resolve,reject)=>{const r=indexedDB.open("pidex-device",1);r.onupgradeneeded=()=>r.result.createObjectStore("identity");r.onerror=()=>reject(r.error);r.onsuccess=()=>resolve(r.result.transaction("identity",mode).objectStore("identity"));});}async function saveDevice(value){const s=await store("readwrite");await new Promise((resolve,reject)=>{const r=s.put(value,"device");r.onsuccess=resolve;r.onerror=()=>reject(r.error);});}async function loadDevice(){const s=await store("readonly");return new Promise((resolve,reject)=>{const r=s.get("device");r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
